// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "iectrl.h"

/////////////////////////////////////////////////////////////////////////////
// CIECtrl

IMPLEMENT_DYNCREATE(CIECtrl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CIECtrl properties

/////////////////////////////////////////////////////////////////////////////
// CIECtrl operations

